[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "superlm"
version = "0.5.0"
description = "SuperLM Model"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "torch>=2.0.0",
    "dotenv>=0.9.9",
    "safetensors>=0.8.0",
]

[tool]

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}

[tool.ruff]
line-length = 120
exclude = ["tests/", "run/"]

[tool.ruff.lint]
select = [
    "ANN",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    "E",
    "F",
    "FBT",
    "FIX",
    "FLY",
    "FURB",
    "G",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PIE",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "TID",
    "TRY",
    "UP",
    "W",
]
ignore = [
    "ANN401",   # any type (why not: sometimes we need)
    "N812",     # lowercase imported as non lowercase (why not: `import torch.nn.functional as F`)
    "PLR0402",  # manual from import (why not: `import torch.nn as nn`)
    "RET504",   # unnecessary assign (why not: beauty)
    "RUF022",   # unsorted dunder all (why not: sorted by category)
    "S101",     # assert (why not: won't use -o mode)
    "SIM115",   # open file with context handler (why not: `open(...).read()`)
]

[tool.ruff.lint.pylint]
max-args = 6
max-positional-args = 6

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F403",     # undefined local with import star
    "F405",     # undefined local with import star usage
]
"config.py" = [
    "FBT003",   # boolean positional value in call
]
"dtypes.py" = [
    "F401",     # unused import
]
"workspace.py" = [
    "F403",     # undefined local with import star
    "F405",     # undefined local with import star usage
]