[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "superlm"
version = "0.5.0"
description = "SuperLM Model"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "torch>=2.2.0",
    "dotenv>=0.9.9",
    "safetensors>=0.8.0",
]

[tool]

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}

[tool.pyright]
typeCheckingMode = "strict"
reportUnknownMemberType = false
ignore = ["**/dtypes.py", "**/tests"]

[tool.mypy]
exclude = ["workspace.py"]

[tool.ruff]
line-length = 100
exclude = ["tests", "run"]

[tool.ruff.lint]
select = [
    "ANN",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    "DOC",
    "E",
    "F",
    "FBT",
    "FIX",
    "FLY",
    "FURB",
    "G",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PIE",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "TID",
    "TRY",
    "UP",
    "W",
]
ignore = [
    "any-type",                             # why not: sometimes we need
    "lowercase-imported-as-non-lowercase",  # why not: `import torch.nn.functional as F`
    "manual-from-import",                   # why not: `import torch.nn as nn`
    "unnecessary-assign",                   # why not: justify
    "unsorted-dunder-all",                  # why not: sorted by category
    "no-self-use",                          # why not: unified interface
    "non-augmented-assignment",             # why not: unsafe on Tensor
]
preview = true

[tool.ruff.lint.pylint]
max-args = 10
max-positional-args = 10

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "undefined-local-with-import-star",
    "undefined-local-with-import-star-usage",
]
"config.py" = [
    "boolean-positional-value-in-call",
    "multiple-spaces-before-operator",
    "multiple-spaces-after-keyword",
]
"dtypes.py" = [
    "unused-import",
]
"workspace.py" = [
    "undefined-local-with-import-star",
    "undefined-local-with-import-star-usage",
    "multiple-spaces-before-operator",
    "too-many-public-methods",
]