[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[project]
name = "superlm"
version = "0.6.0"
description = "SuperLM Model"
readme = "README.md"
authors = [
    { name = "bleuboat", email = "3751541788@qq.com" }
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.14"
dependencies = [
    "torch",
    "dotenv",
    "safetensors",
]

[project.scripts]
superlm = "superlm:main"

[tool]

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}

[tool.pyright]
typeCheckingMode = "strict"
reportUnknownMemberType = false
ignore = ["**/*.in"]

[tool.ruff]
line-length = 100
exclude = ["**/*.in"]
respect-gitignore = false

[tool.ruff.lint]
select = [
    "ANN",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    "DOC",
    "E",
    "F",
    "FBT",
    "FIX",
    "FLY",
    "FURB",
    "G",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PIE",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "TID",
    "TRY",
    "UP",
    "W",
]
ignore = [
    "lowercase-imported-as-non-lowercase",     # why not: `import torch.nn.functional as F`
    "manual-from-import",                      # why not: `import torch.nn as nn`
    "undefined-local-with-import-star",        # why not: `from ... import *`
    "undefined-local-with-import-star-usage",  # why not: `from ... import *`
    "unsorted-dunder-all",                     # why not: sorted by category
    "non-augmented-assignment",                # why not: unsafe on Tensor
]
preview = true

[tool.ruff.lint.pylint]
max-args = 10
max-positional-args = 10

[tool.ruff.lint.per-file-ignores]
"workspace.py" = [
    "too-many-public-methods",
]
"config.py" = [
    "any-type",
    "raise-vanilla-args",
]
"{run,test}/*.py" = [
    "implicit-namespace-package",
]