from superlm import WorkSpace
space = WorkSpace('css', seed=42)
# space.del_checkpoint()
# space.config(special_tokens=('bos', 'eos', 'pad'))
# space.config(n_layer=4, n_embd=64, n_head=4, dropout=0.3)
# space.config(epochs=0.5, block_size=1024, batch_size=2, accumulation_steps=1)
# space.info()
# space.train(length=200)
# space.del_checkpoint()
space.generate(':root', stream=True)