# This file was automatically generated from src\superlm\__init__.py.in
# Do NOT edit this file manually

"""
SuperLM Model
"""

from .workspace import WorkSpace

__version__ = "0.6.0"

__all__ = ["WorkSpace"]
